In [1]:
import numpy as np
import math

In [3]:
a= np.array([1,2,3,4,5]) # Create a 1D numpy array
print(a)
print(a.ndim) # Print the number of dimensions

[1 2 3 4 5]
1


In [4]:
b=np.array([[1,2,3],[4,5,6]]) # Create a 2D numpy array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b.shape  # Get the shape of the array

(2, 3)

In [6]:
a.dtype  # Get the data type of the array elements

dtype('int32')

In [7]:
c=np.array([1.0, 2.0, 3.0])  # Create a float array
c.dtype.name  # Get the data type name

'float64'

In [8]:
c

array([1., 2., 3.])

In [10]:
d=np.zeros((3,4))  # Create an array of zeros
print(d)

e=np.ones((2,3))  # Create an array of ones
print(e)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
np.random.rand(2,3)  # Create an array with random values between 0 and 1

array([[0.80446285, 0.03601935, 0.95551312],
       [0.69191085, 0.55548213, 0.74718685]])

In [12]:
f=np.arange(0,10,2)  # Create an array with a range of values
f

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(0,1,5)  # Create an array with 5 values evenly spaced between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])