In [1]:
import numpy as np
import math

In [2]:
a=np.array([1,3,5,7])
a[2] # Access the third element

5

In [3]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a[1,1] # Access element at second row, second column

4

In [5]:
np.array([a[0,0], a[1,0], a[2,0]])  # Access first column

array([1, 3, 5])

In [6]:
print(a[[0,1,2],[0,1,0]])  # Access elements (0,0), (1,1), (2,0)

[1 4 5]


## Boolean Indexing

In [ ]:
print(a>5) 1# Boolean indexing example

[[False False]
 [False False]
 [False  True]]


In [9]:
print(a[a>5])  # Get elements greater than 5  

[6]


## Slicing

In [10]:
a=np.array([0,1,2,3,4,5])
print(a[:3])  # Slicing: first three elements

[0 1 2]


In [ ]:
print(a[2:4]) # Slicing: elements from index 2 to 3

[2 3]


In [12]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a[:2] # Slicing: first two rows

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a[:2,1:3] # Slicing: first two rows, columns 1 to 2

array([[2, 3],
       [5, 6]])

In [16]:
sub_array = a[0:2, 1:3]
print("sub array index [0,0] value before change:", sub_array[0,0])
sub_array[0,0] = 99
print("sub array index [0,0] value after change:", sub_array[0,0])
print("original array index [0,1] value after change in sub array:", a[0,1])

sub array index [0,0] value before change: 2
sub array index [0,0] value after change: 99
original array index [0,1] value after change in sub array: 99
