In [1]:
import numpy as np
import math

In [2]:
a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])

c=a-b # Element-wise subtraction of two arrays
print(c)
d=a*b # Element-wise multiplication of two arrays
print(d)

[ 9 18 27 36 45]
[ 10  40  90 160 250]


In [ ]:
farenheit = np.array([0, 32, 45, 50, 75, 80, 120])
celsius = (farenheit - 32) * 5.0/9.0 # Convert to Celsius
print(celsius)

[-17.77777778   0.           7.22222222  10.          23.88888889
  26.66666667  48.88888889]


In [ ]:
celsius>0 # Which temperatures are above freezing?

array([False, False,  True,  True,  True,  True,  True])

In [ ]:
celsius%2==0 # Which temperatures are even numbers?

array([False,  True, False,  True, False, False, False])

In [8]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
print(A)
print(B)
print(A*B)  # Element-wise multiplication
print(A@B)  # Matrix multiplication

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [9]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print(array1.dtype)  # Output: int64 (or int32 depending on the system)
array2 = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(array2.dtype)  # Output: float64

int32
float64


In [10]:
array3=array1+array2
print(array3)
print(array3.dtype)  # Output: float64 due to type promotion

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
float64


In [ ]:
# Basic statistical operations
print(array3.sum())        # Sum of all elements
print(array3.min())        # Minimum element
print(array3.max())        # Maximum element
print(array3.mean())       # Mean of all elements

In [13]:
b=np.arange(1,16,1).reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
